source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

pod 'Google-Mobile-Ads-SDK', '~> 7.3.1'
pod 'Masonry', '~> 0.6.1'
pod 'AFNetworking', '~> 2.5.4'
pod 'Colours', '~> 5.6.2'
pod 'CustomBadge', '~> 3.0.0'
pod 'MagicalRecord', '~> 2.3.0'